# Generated by Django 4.2.6 on 2023-11-22 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('selling_price', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('image1', models.ImageField(default=None, upload_to='photos/products/')),
                ('image2', models.ImageField(default=None, upload_to='photos/products/')),
                ('image3', models.ImageField(default=None, upload_to='photos/products/')),
                ('image4', models.ImageField(default=None, upload_to='photos/products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='store.product')),
            ],
            options={
                'verbose_name': 'variation',
                'verbose_name_plural': 'variations',
            },
        ),
    ]
