# Generated by Django 4.2.6 on 2024-01-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="coupon_name",
            field=models.CharField(default="discount coupon", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount",
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="is_available",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="is_expired",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="minimum_amount",
            field=models.IntegerField(default=500, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateField(null=True),
        ),
    ]
