# Generated by Django 4.2.6 on 2024-01-11 05:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_couponusage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CouponUsage",
        ),
    ]
