# Generated by Django 4.2.6 on 2024-01-05 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0007_remove_customuser_referral_customuser_referral_code_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payementwallet",
        ),
    ]
