# Generated by Django 4.2.6 on 2024-01-06 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_payementwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='transaction',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
