# Generated by Django 4.2.3 on 2023-11-15 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sub_Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_category_name", models.CharField(max_length=50, unique=True)),
                (
                    "sub_category_description",
                    models.TextField(default=None, max_length=225),
                ),
                (
                    "sub_Category_image",
                    models.ImageField(default=None, upload_to="photos/sub_categories/"),
                ),
                ("is_activate", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "sub category",
                "verbose_name_plural": "sub categories",
            },
        ),
    ]
