# Generated by Django 4.2.6 on 2024-01-07 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0004_rename_offer_category_category_offer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category_offer",
        ),
    ]
