# Generated by Django 4.2.6 on 2024-01-01 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_coupon"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_applied",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.coupon",
            ),
        ),
    ]
