# Generated by Django 4.2.6 on 2024-01-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_order_coupon_applied"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
