# Generated by Django 4.2.6 on 2024-01-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
