# Generated by Django 4.2.6 on 2024-01-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='offer_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
