# Generated by Django 4.2.6 on 2024-01-11 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_remove_cartitem_discounted_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="applied_to_order",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cart.order",
            ),
        ),
    ]
