# Generated by Django 4.2.6 on 2024-01-11 07:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0007_order_applied_to_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="applied_to_order",
        ),
    ]
